function [fitresult, gof] = createFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'Taylor Reihe' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Apr-2023 09:40:55


%% Fit: 'Taylor Reihe'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( '20*log(a*x^2/(x^2-b))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.438121712548121 0.127703956995974];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'Taylor Reihe' );
% h = plot( fitresult, xData, yData );
% legend( h, 'y vs. x', 'Taylor Reihe', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'x', 'Interpreter', 'none' );
% ylabel( 'y', 'Interpreter', 'none' );
% title()
% grid on


